#!/bin/bash

Rscript -e '
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools", repos = "https://cloud.r-project.org")
}

devtools::install_github("pacificclimate/climdex.pcic")
'
